% opens scripts from a common path in a loop and hard coded paths
pathAppend = 'D:\codeHub\matlab\lv\';


%% loop on file names
names_list = {
    'lv_pipeline'...
    'lv_proc_pipeline'...
    'lv_segment_filter_raw'...
    'lv_clean_segmented'...
    'lv_manual_cleaning'...
    'lv_feature_extractor'...
    'lv_detect_phenomenon'...
    'lv_classify'...
    'lv_post_classification'...
    'lv_build_pipeline'...
    'lv_component_analysis'...
    'lv_examples'...
    'lv_fix_channels'... 
    'lv_align_pipeline'... 
    'lv_trlxtrl_similarity'... 
    'lv_dim_handle'... 
    'lv_EEG_to_CNN'... 
    'lv_BCI_IV1_ft'...
    'lv_mdim_clusterstats'...
    'lv_mdim_pt_stats'...
    }; 
for i=1:length(names_list), edit([pathAppend names_list{i} '.m']); end


%% specifc paths
edit('D:\work\reactivation paper\sent to journal\data and code\on OSF\main code\SWS_classification.m')
edit('D:\work\REM paper\sent to Journal\eLife\after rev\Code on OSF\REM_classification_afterRev.m') 
edit('D:\codeHub\matlab\tia_emotions_classification\Tia_data.m') 